### ISSUE TITLE
Player cant build near Owner

### ISSUE THREAD

**Issue by Grafhugo** [mdsimmo/bomberman#26]
**Describe the bug**
Somehow the player can not build in the Radius of 3 blocks arround an Owner/admin

**Version information**
 - Bomberman Version: v0.6.5
 - Server version: paper 1.16.5
 - Installed plugins: 33 are to much to write, but important ones: Worldguard, Deluxehub 3

**Comment by Grafhugo** [comment]
noted on the server: global-crafter.eu

**Comment by mdsimmo** [comment]
Hey, I'm 99% certain this issue will not be caused by Bomberman, but by some other plugin.

If you can determine what plugin is causing it, then I might be able to write something to make Bomberman compatible, but otherwise, there isn't much I can do.

I'm closing this issue until the plugin is determined.

**Comment by Grafhugo** [comment]
okey, i will look further hahaha 

no idea yet
